# Generated by Django 5.0.2 on 2024-02-13 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_number", models.IntegerField(default=0, editable=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=15)),
                ("last_name", models.CharField(max_length=15)),
                ("id_number", models.IntegerField(default=0)),
                (
                    "id_image",
                    models.ImageField(blank=True, null=True, upload_to="static/media"),
                ),
                ("phone", models.CharField(max_length=10)),
                (
                    "time_in",
                    models.TimeField(
                        default=datetime.datetime(2024, 2, 14, 2, 3, 26, 581735)
                    ),
                ),
                ("time_out", models.TimeField(blank=True, null=True)),
                ("attended", models.BooleanField(default=False)),
            ],
        ),
    ]
