# Generated by Django 5.0.2 on 2024-02-13 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="time_in",
            field=models.TimeField(
                default=datetime.datetime(2024, 2, 14, 2, 4, 6, 223092)
            ),
        ),
    ]
