# Generated by Django 5.0.2 on 2024-02-15 12:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitors", "0002_remove_userprofile_department_admin_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="visitors.department",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("security", "Security Guard"),
                    ("department", "Department Admin"),
                ],
                default="security",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 15, 15, 56, 38, 749334)
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="time_in",
            field=models.TimeField(
                default=datetime.datetime(2024, 2, 15, 15, 56, 38, 749364)
            ),
        ),
    ]
