# Generated by Django 5.0.2 on 2024-02-14 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "visitors",
            "0003_department_remove_visitor_entry_number_visitor_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 14, 3, 41, 29, 962523)
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="time_in",
            field=models.TimeField(
                default=datetime.datetime(2024, 2, 14, 3, 41, 29, 962545)
            ),
        ),
    ]
