# Generated by Django 5.0.2 on 2024-02-14 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitors", "0004_alter_visitor_date_alter_visitor_time_in"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitor",
            name="host",
        ),
        migrations.AlterField(
            model_name="visitor",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 14, 4, 12, 12, 461688)
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="time_in",
            field=models.TimeField(
                default=datetime.datetime(2024, 2, 14, 4, 12, 12, 461714)
            ),
        ),
    ]
