# Generated by Django 5.0.2 on 2024-02-14 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitors", "0005_remove_visitor_host_alter_visitor_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 14, 4, 15, 6, 596107)
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="time_in",
            field=models.TimeField(
                default=datetime.datetime(2024, 2, 14, 4, 15, 6, 596128)
            ),
        ),
    ]
