# Generated by Django 5.0.2 on 2024-02-14 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitors", "0006_alter_visitor_date_alter_visitor_time_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityGuard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_number", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("time_sign_in", models.DateTimeField(blank=True, null=True)),
                ("time_sign_out", models.DateTimeField(blank=True, null=True)),
                (
                    "working_gate",
                    models.CharField(
                        choices=[
                            ("Gate A", "Gate A"),
                            ("Gate B", "Gate B"),
                            ("Gate C", "Gate C"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="visitor",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 14, 4, 54, 19, 975512)
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="time_in",
            field=models.TimeField(
                default=datetime.datetime(2024, 2, 14, 4, 54, 19, 975533)
            ),
        ),
    ]
